spring:
  profiles:
    active: local

# local 환경
---
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data-h2.sql
  config:
    activate:
      on-profile: 
